repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/gitleaks/gitleaks
    rev: 2ca41cc1372d1e939a6a879f18cdc19fc1cac1ce  # frozen: v8.30.0
    hooks:
    -   id: gitleaks

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: e8f7d69b957a30acb2c875078d5fd012de24b64c  # frozen: v0.16.7
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 7ff8d35ae36a7d2b968f2f90b4c723e292e594ee  # frozen: v2.3.1
    hooks:
    -   id: mypy

-   repo: https://github.com/semgrep/semgrep
    rev: f0de20ae7f8a50f8e7c6e64474b55c0f59ddf69c  # frozen: v1.165.0
    hooks:
    -   id: semgrep
        args:
        - --config
        - p/python
